# Exercise 4

### Necessary imports

In [21]:
import os
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestCentroid
import numpy as np

### Dataset loading

In [16]:
directory = 'dataset/20_NGs_400'
list_of_vectors = []

for filenames in os.listdir(directory):
    for file in os.listdir(directory + "/" + filenames):
        f = open(directory + "/" + filenames + "/" + file, "r")
        list_of_vectors.append(f.read())

### Creating the FVM with TF-IDF weighting

In [29]:
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(list_of_vectors)

target = []
for i in range(20):
    for j in range(20):
        target.append(i)

In [67]:
# Profilo di una classe di documenti
# D un seti di documenti 
# T un dizionarion con tutti le parole univoche
# Td un vettore che per ogni parole contiene tutte le frequenze
# centroide = somma di tutti i vettori che contengono delle parole * 1/X (dove X e in insieme di permine)

# F_ki = k-features e i classe 
# W_kj = parola appartente al documento j

# train [[0,1,0,...,3,2,0]]
# target [0,0,0,0,0,...1,1,1,1,1....2,2,2,2]

def rocchio_method(train:list, target:list, num_class:int, beta:int, gamma:int):
    c = []
    for i in range(num_class):
        pos = []
        neg = []
        pos_word_num = []
        neg_word_num = []
        for index, x in enumerate(train):
            if(target[index] == i):
                pos.append(x)
            else:
                neg.append(x)
        pos_word_num = np.array([sum(x) for x in zip(*pos)])
        neg_word_num = np.array([sum(x) for x in zip(*neg)])

        c.append((beta * (pos_word_num)) - (gamma * neg_word_num))
    return c

In [66]:
c = rocchio_method(X.toarray(), target, 20, 16, 4)

[0 0 0 ... 0 1 0]
[62 87  1 ...  2  0  1]
5490
100403
[0 0 0 ... 0 0 0]
[62 87  1 ...  2  1  1]
1709
104184
[2 0 0 ... 0 0 0]
[60 87  1 ...  2  1  1]
3098
102795
[1 0 0 ... 0 0 0]
[61 87  1 ...  2  1  1]
1974
103919
[0 2 0 ... 0 0 0]
[62 85  1 ...  2  1  1]


KeyboardInterrupt: 